server:
  port: 8081
spring: 
  datasource:
    dataSourceClassName: com.mysql.jdbc.Driver #(com.mysql.jdbc.jdbc2.optional.MysqlDataSource)
    url: jdbc:mysql://192.168.2.31/sc_boot
    username: root
    password: root
    initialSize: 10
    maxActive: 50
    minIdle: 5
    maxWait: 60000
    validationQuery: select 1
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 10
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 25200000
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    logAbandoned: true
    filters: stat
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    openInView: true
    show_sql: true
    generate-ddl: true #(false)
    hibernate:
        ddl-auto: update #(none)
        #naming-strategy: org.hibernate.config.EJB3NamingStrategy #影响表和字段名称，表中列名和字段名称
    properties:
       hibernate.cache.use_second_level_cache: true
       hibernate.cache.use_query_cache: false
       hibernate.generate_statistics: false
       #hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory